export enum RankEnum {
  soldier = "Солдат",
  juniorSergeant = "Молодший сержант",
  sergeant = "Сержант",
  seniorSergeant = "Старший сержант",
  sergeantMajor = "Старшина",
  juniorWarrantOfficer = "Прапорщик",
  warrantOfficer = "Старший прапорщик",
  juniorLieutenant = "Молодший лейтенант",
  lieutenant = "Лейтенант",
  seniorLieutenant = "Старший лейтенант",
  captain = "Капітан",
  major = "Майор",
  lieutenantColonel = "Підполковник",
  colonel = "Полковник",
  brigadierGeneral = "Бригадний генерал",
  majorGeneral = "Генерал-майор",
  lieutenantGeneral = "Генерал-лейтенант",
  generalOfTheArmyOfUkraine = "Генерал армії України"
}